# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.spawn_variant_1.frame dummy
scoreboard objectives add aj.spawn_variant_2.frame dummy
scoreboard objectives add aj.spawn_variant_3.frame dummy
scoreboard objectives add aj.spawn_variant_4.frame dummy
scoreboard objectives add aj.spawn_variant_5.frame dummy
scoreboard objectives add aj.spawn_variant_secret.frame dummy