# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_giftbox) { transformation: [0.00001f,0f,-2.4492935982947065e-21f,0.5f,0f,0.00001f,0f,0.25f,2.4492935982947065e-21f,0f,0.00001f,-0.31249999999999994f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_head) { transformation: [1f,0f,-2.4492935982947064e-16f,0.43750000000000006f,0f,1f,0f,-0.25f,2.4492935982947064e-16f,0f,1f,-0.31249999999999994f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_body) { transformation: [1f,0f,-2.4492935982947064e-16f,0.5f,0f,1f,0f,0.25f,2.4492935982947064e-16f,0f,1f,-0.31249999999999994f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_right_arm) { transformation: [0.8660254037844385f,0.26864980417341205f,-0.421695722906443f,0.53125f,0f,0.8433914458128857f,0.537299608346824f,0.25f,0.5000000000000002f,-0.4653151102717789f,0.7303984174084457f,-0.37499999999999994f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }
$data merge entity $(bone_left_arm) { transformation: [0.8660254037844387f,-0.26864980417341183f,0.4216957229064427f,0.5625f,0f,0.8433914458128857f,0.537299608346824f,0.109375f,-0.4999999999999998f,-0.465315110271779f,0.7303984174084459f,-0.5624999999999999f,0f,0f,0f,1f], start_interpolation: 0, interpolation_duration: 1 }

particle block{block_state:packed_ice} ^ ^-0.1 ^-0.2 0.2 0.1 0.2 0.1 30 force
playsound block.glass.hit master @a ~ ~ ~ 1 1.2