# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.elf.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'elf', 'function_path': 'animated_java:elf/variants/orange/apply'}
execute on passengers if entity @s[tag=aj.elf.bone.giftbox] run function animated_java:elf/variants/orange/zzz/0
execute on passengers if entity @s[tag=aj.elf.bone.head] run function animated_java:elf/variants/orange/zzz/1
execute on passengers if entity @s[tag=aj.elf.bone.body] run function animated_java:elf/variants/orange/zzz/2
execute on passengers if entity @s[tag=aj.elf.bone.right_arm] run function animated_java:elf/variants/orange/zzz/3
execute on passengers if entity @s[tag=aj.elf.bone.left_arm] run function animated_java:elf/variants/orange/zzz/4