# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.elf.root] run return 0
execute on passengers if entity @s[tag=aj.elf.data] unless data entity @s {data:{rigHash: 'b4295f6134803c00d40ab3c71d0d3ad9842e60b8a1614d0186232d313d1ff1c0'}} on vehicle run function animated_java:elf/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1