# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.elf.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:elf/as_root/pre_tick
execute if entity @s[tag=aj.elf.animation.spawn.playing] run function animated_java:elf/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_1.playing] run function animated_java:elf/animations/spawn_variant_1/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_2.playing] run function animated_java:elf/animations/spawn_variant_2/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_3.playing] run function animated_java:elf/animations/spawn_variant_3/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_4.playing] run function animated_java:elf/animations/spawn_variant_4/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_5.playing] run function animated_java:elf/animations/spawn_variant_5/zzz/on_tick
execute if entity @s[tag=aj.elf.animation.spawn_variant_secret.playing] run function animated_java:elf/animations/spawn_variant_secret/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:elf/as_root/post_tick