# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.elf.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'elf', 'function_path': 'animated_java:elf/animations/pause_all'}
tag @s remove aj.elf.animation.spawn.playing
tag @s remove aj.elf.animation.spawn_variant_1.playing
tag @s remove aj.elf.animation.spawn_variant_2.playing
tag @s remove aj.elf.animation.spawn_variant_3.playing
tag @s remove aj.elf.animation.spawn_variant_4.playing
tag @s remove aj.elf.animation.spawn_variant_5.playing
tag @s remove aj.elf.animation.spawn_variant_secret.playing